openapi: 3.0.3
info:
  title: User Service
  version: 0.0.1
servers:
  - url: https://user-service.dajohnston.co.uk/api/v1
  - url: http://localhost:3000/api/v1
tags:
  - name: user-info
    description: Operations about user-info
paths:
  /user-info:
    get:
      tags:
        - user-info
      summary: Get details of requesting user.
      description: Get details of the requesting user.
      operationId: getUserInfo
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - user-info
      summary: Update the details of the requesting user.
      description: Update the details of the requesting user.
      operationId: updateUserInfo
      requestBody:
        description: Partial details of user info to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchUserInfo'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /households:
    get:
      tags:
        - households
      summary: Get households this user belongs to.
      description: Get households this user belongs to.
      operationId: getUserHouseholds
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Household'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - households
      summary: Create a new household
      description: Create a new household
      operationId: createUserHousehold
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Household'
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Household'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /households/{id}:
    delete:
      tags:
        - households
      summary: delete a household by id
      description: delete a household by id
      operationId: deleteUserHousehold
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        204:
          description: success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - households
      summary: update a household by id
      description: update a household by id
      operationId: updateUserHousehold
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchableHousehold'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Household'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    BaseUser:
      type: object
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          example: john.doe@email.com
          readOnly: true
        nickname:
          type: string
          example: JD
        gravatarEmailAddress:
          type: string
          example: david@gravatar.com
        picture:
          type: string
          example: https://my-picture.com
        avatarImageSource:
          $ref: '#/components/schemas/AvatarImageSource'
    UserInfo:
      allOf:
        - $ref: '#/components/schemas/BaseUser'
      required:
        - firstName
        - lastName
        - email
        - avatarImageSource
        - nickname
        - gravatarEmailAddress
        - picture
    PatchUserInfo:
      allOf:
        - $ref: '#/components/schemas/BaseUser'
      minProperties: 1
    AvatarImageSource:
      type: string
      enum:
        - GRAVATAR
        - MANUAL
    HouseholdMember:
      type: object
      required:
        - id
        - user_id
        - role
        - joined_at
      properties:
        id:
          type: integer
        user_id:
          type: string
        role:
          type: string
        joined_at:
          type: string
          format: date-time
    BaseHousehold:
      type: object
      additionalProperties: false
      required:
        - id
        - created_at
        - created_by
        - updated_at
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        created_by:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        members:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/HouseholdMember'
    Household:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseHousehold'
      required:
        - name
    PatchableHousehold:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseHousehold'
      minProperties: 1
    Error:
      type: object
      properties:
        status:
          type: number
        message:
          type: string
  securitySchemes:
    auth0_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://dajohnston.eu.auth0.com/authorize?audience=https://user-service.dajohnston.co.uk
          scopes:
            'openid': openid
            'profile': profile
            'offline_access': offline access
security:
  - auth0_auth: []